services:
  php:
    build: .
    container_name: pc-php
    ports:
      - "8082:80"
    volumes:
      - ./project:/var/www/html
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://hernan:secret@mysql:3306/challengephp

  mysql:
    image: mysql:8.0
    container_name: pc-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: challengephp
      MYSQL_USER: hernan
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
